#!/bin/bash
# python_service/scripts/examples.sh

# Ejemplos de uso del script fetch_historical_data.py

echo "=== EJEMPLOS DE USO DEL DATA FETCHER ==="
echo ""

echo "1. 🆓 DATOS GRATUITOS (Recomendado para empezar)"
echo "   Obtiene datos de Football-Data.co.uk - Completamente gratis"
echo ""
echo "   Comando:"
echo "   python fetch_historical_data.py --source free --leagues \"Premier League\" \"La Liga\" --seasons 2022 2023 2024"
echo ""

echo "2. 🔬 DATOS DE MUESTRA (Para testing)"
echo "   Genera datos sintéticos realistas para probar el modelo"
echo ""
echo "   Comando:"
echo "   python fetch_historical_data.py --source sample"
echo ""

echo "3. 💰 DATOS PREMIUM (Requiere API key)"
echo "   Obtiene datos de API-Football - Más precisos y completos"
echo ""
echo "   Comando:"
echo "   python fetch_historical_data.py --source api --api-key TU_API_KEY --leagues \"Premier League\" --seasons 2023 2024"
echo ""

echo "4. 📊 CONFIGURACIÓN PERSONALIZADA"
echo "   Especifica ligas, temporadas y archivo de salida"
echo ""
echo "   Comando:"
echo "   python fetch_historical_data.py \\"
echo "     --source free \\"
echo "     --leagues \"Premier League\" \"La Liga\" \"Bundesliga\" \"Serie A\" \\"
echo "     --seasons 2021 2022 2023 2024 \\"
echo "     --output mi_dataset_personalizado.csv"
echo ""

echo "=== PASOS RECOMENDADOS PARA EMPEZAR ==="
echo ""

echo "Paso 1: Instalar dependencias"
echo "pip install pandas numpy requests"
echo ""

echo "Paso 2: Crear directorio de datos"
echo "mkdir -p python_service/data"
echo ""

echo "Paso 3: Ejecutar con datos gratuitos (recomendado)"
echo "cd python_service/scripts"
echo "python fetch_historical_data.py --source free"
echo ""

echo "Paso 4: Verificar datos obtenidos"
echo "ls -la ../data/"
echo "head -n 5 ../data/partidos_historicos.csv"
echo ""

echo "=== FUENTES DE DATOS DISPONIBLES ==="
echo ""

echo "🟢 GRATUITAS:"
echo "  • Football-Data.co.uk: Ligas europeas principales (1993-2024)"
echo "  • Datos sintéticos: Para testing y desarrollo"
echo ""

echo "🟡 PREMIUM (Requieren registro/pago):"
echo "  • API-Football: Datos oficiales, estadísticas detalladas"
echo "  • The Sports DB: API gratuita con límites"
echo ""

echo "🔵 ALTERNATIVAS:"
echo "  • Kaggle: European Soccer Database (descarga manual)"
echo "  • GitHub: Repositorios con datos históricos"
echo "  • Web Scraping: ESPN, BBC Sport (implementar cuidadosamente)"
echo ""

echo "=== OBTENER API KEY GRATUITA ==="
echo ""
echo "Para API-Football (100 requests/día gratis):"
echo "1. Visita: https://rapidapi.com/api-sports/api/api-football"
echo "2. Registrate en RapidAPI"
echo "3. Suscríbete al plan gratuito"
echo "4. Copia tu X-RapidAPI-Key"
echo "5. Úsala con: --api-key TU_CLAVE"
echo ""

echo "=== ESTRUCTURA DE DATOS GENERADOS ==="
echo ""
echo "El CSV generado tendrá estas columnas:"
echo "  • match_id: ID único del partido"
echo "  • date: Fecha del partido (YYYY-MM-DD)"
echo "  • season: Temporada (año)"
echo "  • league: Nombre de la liga"
echo "  • home_team, away_team: Nombres de equipos"
echo "  • home_goals, away_goals: Goles marcados"
echo "  • result: H (local), D (empate), A (visitante)"
echo "  • total_goals: Total de goles del partido"
echo "  • [estadísticas adicionales según la fuente]"
echo ""

echo "=== SOLUCIÓN DE PROBLEMAS ==="
echo ""
echo "❌ Error 'No module named pandas':"
echo "   Solución: pip install pandas numpy requests"
echo ""
echo "❌ Error 'API key inválida':"
echo "   Solución: Verifica tu clave en RapidAPI"
echo ""
echo "❌ Error 'No se obtuvieron datos':"
echo "   Solución: Verifica conexión a internet y parámetros"
echo ""
echo "❌ Error de permisos:"
echo "   Solución: chmod +x fetch_historical_data.py"
echo ""

echo "=== PRÓXIMOS PASOS DESPUÉS DE OBTENER DATOS ==="
echo ""
echo "1. Verificar calidad de datos:"
echo "   python -c \"import pandas as pd; df=pd.read_csv('data/partidos_historicos.csv'); print(df.info())\""
echo ""
echo "2. Entrenar modelo:"
echo "   python train_model.py --data data/partidos_historicos.csv"
echo ""
echo "3. Evaluar modelo:"
echo "   python -c \"from models.model_evaluation import ModelEvaluator; print('Listo para evaluar')\""
echo ""

echo "¡Listo para obtener datos históricos! 🚀"